version: "3"

services:
  myjupyter:
    image: quay.io/jupyter/minimal-notebook:lab-4.1.6
    ports:
      - 8888:8888
    volumes:
      - ./work:/home/jovyan/work
    environment:
      - JUPYTER_TOKEN=odsc