version: "3"

services:

  # cloud storage
  minio:
    image: minio/minio:RELEASE.2023-02-10T18-48-39Z
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: miniopassword
    volumes:
      - ./data:/data
    networks:
      - default

  # Build the data generator
  datagen:
    build: ./pipeline/
    command: python -m streamlit run /app/datagenerator.py --server.port 8501
    environment:
      MINIO_URL: http://minio:9000
      MINIO_USER: minioadmin
      MINIO_PASSWORD: miniopassword
      MINIO_BUCKET: data
      DATA_SOURCE: companydata.csv
      DATA_TARGET: dashboarddata.csv
    ports:
      - 8001:8501

  # build The dashboard
  dashboard:
    build: ./pipeline/
    command: python -m streamlit run /app/dashboard.py --server.port 8502
    environment:
      MINIO_URL: http://minio:9000
      MINIO_USER: minioadmin
      MINIO_PASSWORD: miniopassword
      MINIO_BUCKET: data
      DATA_SOURCE: companydata.csv
      DATA_TARGET: dashboarddata.csv
    ports:
      - 8002:8502

  # Dev container
  pipeline:
    image: mcr.microsoft.com/devcontainers/python:1-3.11-bookworm
    environment:
      MINIO_URL: http://minio:9000
      MINIO_USER: minioadmin
      MINIO_PASSWORD: miniopassword
      MINIO_BUCKET: data
      DATA_SOURCE: companydata.csv
      DATA_TARGET: dashboarddata.csv
    networks:
      - default

networks:
  default:
    driver: bridge
